import {sky,type SkyEntry} from './sky';import type {Locale} from './i18n';
// Source spellings are retained rather than silently standardised to a dialect.
// Quechua prose is a working translation, not linguistically reviewed.
const es:Record<string,[string,string,string,string,string,string]>={
 inti:['Sol','Estrella','Inti','El Sol: una referencia para los ciclos del año.','Inti es el Sol, honrado en la religión inka y en Inti Raymi. Las observaciones solares ayudaban a reconocer los ciclos estacionales.','Marca la punta de la sombra de un palo a distintas horas. Nunca mires directamente al Sol ni lo busques con binoculares o telescopio.'],
 killa:['Luna','Satélite natural','Killa · Quilla · Mama Quilla (nombre religioso)','Su aspecto cambia a lo largo del mes.','Mama Quilla aparece en relatos de la religión inka. Conservamos Killa y Quilla como formas escritas documentadas, sin imponer una grafía a todas las comunidades.','Comprueba la salida y puesta de la Luna para tu lugar y fecha. Dibuja su forma y compárala otra noche: no es visible todas las tardes.'],
 chasca:['Venus','Planeta','Chasca en Garcilaso · Ch’aska en otras grafías','Un planeta brillante que puede verse al amanecer o al anochecer.','Garcilaso registra Chasca para Venus. Es un testimonio colonial; no demuestra que todas las comunidades actuales usen el nombre de la misma manera.','Busca Venus en un planetario con tu fecha y lugar. Obsérvalo solo cuando el Sol esté bajo el horizonte. Nunca busques cerca del Sol con instrumentos ópticos.'],
 collca:['Pléyades · M45','Cúmulo de estrellas','Collca · Colca · Qollqa','Un grupo de estrellas relacionado con el calendario agrícola.','Aquí Collca se refiere a las Pléyades. La identificación no es única: el artículo de PUCP también registra Collca para grupos en Escorpio y las Híades. No confundas una equivalencia de esta ficha con un nombre universal.','Busca M45 en Stellarium. Si está sobre el horizonte después de oscurecer, busca un pequeño grupo compacto. Para practicar con binoculares, espera a que el Sol esté bajo el horizonte.'],
 alpha:['Alpha Centauri','Sistema estelar','Llamaq ñawin · Llamap / Llamapa ñawin (formas regionales)','Una de las dos luces identificadas como los ojos de la llama.','Alpha y Beta Centauri forman el par llamado ojos de la llama en los relatos citados. No son dos nombres tradicionales distintos ni un solo sistema estelar.','Busca Alpha Centauri con fecha y lugar en Perú. Comprueba su altura sobre el horizonte: una montaña puede ocultarla aunque el mapa la sitúe sobre el horizonte ideal.'],
 beta:['Beta Centauri','Sistema estelar','Llamaq ñawin · nombre compartido por el par','La otra luz del par de ojos de la llama.','Beta Centauri comparte el nombre con Alpha Centauri. Su proximidad aparente en el cielo no significa que estén cerca una de otra en el espacio.','Busca Beta Centauri y compara su posición con Alpha Centauri, cerca de la región de la Cruz del Sur. Comprueba la fecha, hora y obstáculos del horizonte.'],
 mayu:['Vía Láctea','Galaxia / franja celeste','Mayu · río','Un río celeste de zonas luminosas y oscuras.','Mayu significa río. La franja que vemos es nuestra galaxia desde dentro; las figuras oscuras se reconocen en regiones de polvo que ocultan parte de su luz. La interpretación cultural y la descripción astronómica tienen contextos distintos.','Busca un lugar oscuro y un horario sin Luna. Verifica la posición de la franja para tu fecha. Las fotos muestran más color y contraste que el ojo humano.'],
 llama:['Llama oscura','Figura de polvo oscuro','Llama · figura, no estrella individual','Una figura oscura con dos ojos brillantes.','Las fuentes citadas identifican los ojos con Alpha y Beta Centauri. Los contornos culturales no son límites oficiales de constelaciones astronómicas.','Localiza las dos estrellas en un mapa y estudia después las zonas oscuras de la Vía Láctea. Usa una fotografía si las luces o las nubes impiden verlas.'],
 yutu:['Tinamú / perdiz','Figura de polvo oscuro','Yutu · frecuentemente traducido como perdiz','Un ave asociada a una región oscura cercana a la Cruz del Sur.','La guía GLORIA vincula Yutu con el Saco de Carbón. Es una región oscura, no un dibujo hecho al unir estrellas.','Busca la Cruz del Sur y el Saco de Carbón en un mapa situado en Perú. Hace falta un cielo oscuro y despejado; verifica que estén sobre el horizonte.'],
 hanpata:['Sapo','Figura de polvo oscuro','Hanp’ata · grafía de la fuente citada','Un sapo reconocido en las zonas oscuras del río celeste.','Hanp’ata figura en la guía GLORIA. No atribuimos a esta figura un contorno universal ni un relato único de todas las comunidades.','Explora una fotografía amplia de la Vía Láctea. Para identificar interpretaciones locales, pide orientación a alguien de la comunidad y registra la fuente.'],
 machacuay:['Serpiente','Figura de polvo oscuro','Machacuay · grafía de la fuente citada','Una serpiente reconocida en el fondo oscuro de Mayu.','Machacuay aparece entre las figuras oscuras de la guía citada. Conservamos la grafía de esa fuente; los nombres pueden variar.','Compara regiones luminosas y oscuras en una fotografía. Para observar al aire libre, necesitas pocas luces, poco brillo lunar y un cielo despejado.']
};
const qu:typeof es={
 inti:['Inti','Quyllur','Inti','Intiqa watapa puriyninta riqsichin.','Intiqa Inka yachaypi yupaychasqam. Inti Raymipi Intita yuyarinku.','Kaspipa llant’unta huk pachapi, huk pachapipas siq’iy. Ama Intita chiqanta qhawaychu, binoculares nisqawanpas ama qhawaychu.'],
 killa:['Killa','Pachapa muyuq masin','Killa · Quilla · Mama Quilla','Killapa rikch’aynin t’ikrakun.','Inka yachaymanta qillqakunapi Mama Quilla suti kan. Killa, Quilla qillqaykuna pukyukunapi kachkan.','Maypi, hayk’aq Killa lluqsimun, chinkan chayta qhaway. Rikch’ayninta siq’iy; huk tutapi tinkuchiy. Manam sapa tutachu rikukun.'],
 chasca:['Venus','Planeta','Garcilasopi Chasca · Ch’aska','Paqarinpi utaq tutayaypi k’anchaq planeta.','Garcilasoqa Venus nisqata Chasca sutichan. Kayqa ñawpa qillqam; manam llapan kunan llaqtapa sutichayninchu.','Planetariopi Venus nisqata maskhay. Inti chinkasqaña kaptin qhaway. Ama Intipa qayllanpi binoculares nisqawan maskhaychu.'],
 collca:['Pléyades · M45','Quyllur huñu','Collca · Colca · Qollqa','Chakra wataman t’inkisqa quyllur huñu.','Kaypi Collcaqa Pléyades nisqakunam. PUCP qillqapi Escorpio, Híades huñukunapaqpas Collca suti kan. Manam huk huñullapa sutichu.','Stellarium nisqapi M45 nisqata maskhay. Tutapi hanaqpi kaptin huch’uy quyllur huñuta qhaway. Binoculares nisqata Inti chinkasqaña kaptin llamk’achiy.'],
 alpha:['Alpha Centauri','Quyllur sistema','Llamaq ñawin · Llamap / Llamapa ñawin','Llamapa iskay ñawinmanta huknin.','Alpha, Beta Centauri nisqakuna llamapa ñawinkuna hina riqsisqam. Kay suti iskayninkupaqmi, manam sapankapaq huk sutichu.','Perúpi kasqaykita, punchawta, pachatawan churaspa Alpha Centauri nisqata maskhay. Urqukuna pakayta atinku.'],
 beta:['Beta Centauri','Quyllur sistema','Llamaq ñawin · iskayninpa sutin','Llamapa huk ñawin.','Beta Centauri, Alpha Centauriwan kuska kay sutiyuqmi. Hanaq pachapi qaylla rikukuspankupas, karupim kanku.','Beta Centauri, Alpha Centauriwan maypi kasqanta qhaway. Punchawta, pachata, urqukunatawan qhaway.'],
 mayu:['Mayu / Vía Láctea','Galaxia','Mayu','K’anchaq, yana kitiyuq hanaq pacha mayu.','Mayuqa mayu ninanmi. Galaxianchikpa ukhullanmanta k’anchayninta rikunchik. Yana kitikunapi ñut’u allpa k’anchayta pakan.','Tutayaq kitita, mana Killa k’anchaq pachata akllay. Mayu maypi kasqanta mapapi qhaway. Siq’ipi aswan k’anchay, llimp’ipas rikukun.'],
 llama:['Yana llama','Yana rikch’a','Llama · manam sapallan quyllurchu','Iskay k’anchaq ñawiyuq yana llama.','Pukyukunapi Alpha, Beta Centauri nisqakuna llamapa ñawinkunam. Rikch’apa sayaynin manam llapapaq hukllachu.','Iskay quyllurkunata maskhay; chaymanta Mayupa yana kitinkunata qhaway. Phuyu kaptin siq’ita llamk’achiy.'],
 yutu:['Yutu','Yana rikch’a','Yutu · perdiz nisqapas','Cruz del Sur qayllapi yana kitiman t’inkisqa pisqu.','GLORIA qillqa Yututa Saco de Carbón nisqaman t’inkin. Kayqa yana kitim; manam quyllurkunata huñuspa rurasqa siq’ichu.','Perúpa mapanpi Cruz del Sur, Saco de Carbón nisqakunata maskhay. Tutayaq, mana phuyuyuq hanaq pachata munanki.'],
 hanpata:['Hanp’ata','Yana rikch’a','Hanp’ata · pukyupi qillqasqa','Mayupa yana kitinpi hanp’ata.','GLORIA qillqapi Hanp’ata suti kan. Manam llapan llaqtapaq huk rikch’allata, huk willakuyllata churanchikchu.','Mayupa hatun siq’inta qhaway. Llaqtapa yachayninta riqsinaykipaq runakunata tapuy; pukyuta qillqay.'],
 machacuay:['Machacuay / mach’aqway','Yana rikch’a','Machacuay · pukyupi qillqasqa','Mayupa yana kitinpi mach’aqway.','Machacuayqa GLORIA qillqapi yana rikch’akunamanta hukninmi. Pukyupa qillqayninta waqaychanchik; sutikuna hukniray kanman.','Siq’ipi k’anchaq, yana kitikunata tinkuchiy. Hawapi qhawanapaq pisi k’anchayta, mana phuyuyuq hanaq pachata munanki.']
};
export function localizedSky(locale:Locale):SkyEntry[]{return sky.map(e=>{if(locale==='en')return e;const [english,kind,variants,summary,story,observe]=(locale==='es'?es:qu)[e.id];return {...e,english,kind,variants,summary,story,observe}})}
export function searchText(id:string){const e=sky.find(e=>e.id===id)!;return [e.id,e.name,e.english,...es[id].slice(0,3),...qu[id].slice(0,3)].join(' ').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
