export const sources={
 gloria:{name:"GLORIA · Astronomy of the Incas, pp. 8–10",url:"https://cordis.europa.eu/docs/projects/cnect/3/283783/080/deliverables/001-D210lunareclipseactivity2v02A.pdf"},
 smithsonian:{name:"Smithsonian · Reciprocity—Andean Style",url:"https://americanindian.si.edu/nk360/inka-water/reciprocity/reciprocity"},
 garcilaso:{name:"Garcilaso · Comentarios reales, Book III, ch. XXI",url:"https://www.biblioteca-antologica.org/es/wp-content/uploads/2021/07/GARCILASO-EL-INCA-Comentarios-reales-I-Parte.pdf"},
 pucp:{name:"PUCP · Anthropologica, note on Llamacñawin",url:"https://revistas.pucp.edu.pe/index.php/anthropologica/article/download/6311/6355/"},
 nasa:{name:"NASA · Stargazing for Beginners",url:"https://science.nasa.gov/solar-system/skywatching/night-sky-network/may2024-night-sky-notes/"},
 stellarium:{name:"Stellarium · User Guide",url:"https://stellarium.org/guide/"}
};
export type SkyEntry={id:string;name:string;english:string;kind:string;group:"lights"|"dark";variants:string;summary:string;story:string;observe:string;source:(keyof typeof sources)[];symbol:string};
export const sky:SkyEntry[]=[
{id:"inti",name:"Inti",english:"Sun",kind:"Star",group:"lights",variants:"Inti",symbol:"sun",summary:"A sacred presence at the heart of the Inka seasonal calendar.",story:"Inti is the Sun, honoured in Inka religion and in the continuing festival of Inti Raymi. Observations of the Sun helped mark the seasons.",observe:"Explore Inti through shadows. Mark the tip of a stick’s shadow at different times; never look directly at the Sun, especially through binoculars or a telescope.",source:["smithsonian","gloria"]},
{id:"killa",name:"Killa",english:"Moon",kind:"Natural satellite",group:"lights",variants:"Quilla · Mama Quilla (religious name)",symbol:"moon",summary:"A changing face in the sky, linked with the passage of time.",story:"Mama Quilla appears in accounts of Inka religion as the Moon Mother. Killa and Quilla are different written forms; local usage matters.",observe:"Check a current sky chart for moonrise and moonset. Sketch the shape you see, then return on another night and compare. The Moon is not visible every evening.",source:["gloria"]},
{id:"chasca",name:"Chasca",english:"Venus",kind:"Planet",group:"lights",variants:"Chasca in Garcilaso’s account; often written Ch’aska",symbol:"spark",summary:"The brilliant light that can appear near dawn or after sunset.",story:"Garcilaso records Chasca as a name for Venus and describes it as accompanying the Sun. This is a colonial-era account, not a universal dictionary of present-day Quechua traditions.",observe:"Search for Venus in a planetarium set to your date and location. When visible, look toward the indicated horizon after sunset or before sunrise. Avoid searching with optics near the Sun.",source:["garcilaso"]},
{id:"collca",name:"Collca",english:"Pleiades · M45",kind:"Star cluster",group:"lights",variants:"Colca · Qollqa",symbol:"cluster",summary:"A small gathering of stars, connected with the agricultural year.",story:"The Pléiades are linked to Andean agricultural calendars and festivals. Collca is associated with the idea of a storehouse. Names and interpretations vary between sources and communities.",observe:"Search M45 in Stellarium. When above the horizon after dark, look for a tiny, close group of stars. Binoculars can reveal more stars; use them only when the Sun is safely below the horizon.",source:["smithsonian","gloria"]},
{id:"alpha",name:"Llamaq ñawin",english:"Alpha Centauri",kind:"Star system",group:"lights",variants:"One of the llama’s eyes · also Llamap/Llamapa ñawin in Ayacucho forms",symbol:"star",summary:"One of the two bright stars understood as the eyes of the llama.",story:"Alpha and Beta Centauri together are identified as the llama’s eyes in documented Andean traditions. This name refers to the pair, not a separate traditional name unique to Alpha Centauri.",observe:"A southern-sky target. Search Alpha Centauri at your location and time. It never rises at many northern latitudes; use a Cusco simulation if it is unavailable where you live.",source:["pucp","gloria"]},
{id:"beta",name:"Llamaq ñawin",english:"Beta Centauri",kind:"Star system",group:"lights",variants:"The other llama’s eye · a shared name for the pair",symbol:"star",summary:"The companion eye in an animal traced through the Milky Way.",story:"Beta Centauri is the other bright eye paired with Alpha Centauri. Their appearance together in the sky does not mean the two are close neighbours in space.",observe:"Search Beta Centauri in Stellarium and find Alpha Centauri nearby in the sky. These stars lie near the Southern Cross region; visibility depends strongly on latitude.",source:["pucp","gloria"]},
{id:"mayu",name:"Mayu",english:"Milky Way",kind:"Galaxy / sky band",group:"lights",variants:"Mayu · river",symbol:"river",summary:"A celestial river with figures hidden in its dark spaces.",story:"Mayu is the celestial river. Andean observers recognised both bright stars and figures in the dark patches of its band. Seeing this band is different from knowing its modern scientific description as our galaxy.",observe:"Choose a dark, moonless night and allow your eyes to adjust. Look for a faint broad band. Use a local sky chart to check its position; photographs show much more colour and contrast than the unaided eye.",source:["gloria"]},
{id:"llama",name:"Llama",english:"Dark-cloud llama",kind:"Dark constellation",group:"dark",variants:"Llama · a figure, not an individual star",symbol:"dark",summary:"A dark figure with Alpha and Beta Centauri as its bright eyes.",story:"The GLORIA account places a dark llama along the Milky Way and identifies Alpha and Beta Centauri as its eyes. Outlines in modern illustrations are interpretations, not fixed astronomical boundaries.",observe:"Begin by locating the two Centauri stars, then study the dark regions along the Milky Way. A genuinely dark sky is essential; a photograph or planetarium can support a classroom discussion.",source:["gloria","pucp"]},
{id:"yutu",name:"Yutu",english:"Tinamou / partridge",kind:"Dark constellation",group:"dark",variants:"Yutu; commonly translated as partridge",symbol:"dark",summary:"A bird found in a dark patch near the Southern Cross.",story:"The Coalsack dark region, close to the Southern Cross, is associated with Yutu in the cited teaching account. The figure is made from a dark area, not lines joining stars.",observe:"Locate the Southern Cross using a date-specific chart, then the nearby Coalsack. Both are southern-sky targets. Do not expect to see them from every latitude.",source:["gloria"]},
{id:"hanpata",name:"Hanp’ata",english:"Toad",kind:"Dark constellation",group:"dark",variants:"Hanp’ata in the cited source; other spellings occur",symbol:"dark",summary:"A small animal imagined in the darkness of the celestial river.",story:"The GLORIA guide records Hanp’ata among the dark-cloud animals of Andean astronomy. Community names and the details of associated stories should be attributed locally.",observe:"Use a wide Milky Way photograph or a guided southern-sky session to explore the dark areas. This catalogue does not assign an exact, universally agreed outline to the toad.",source:["gloria"]},
{id:"machacuay",name:"Machacuay",english:"Snake",kind:"Dark constellation",group:"dark",variants:"Machacuay in the cited source",symbol:"dark",summary:"A snake recognised in dark regions along the Milky Way.",story:"Machacuay appears alongside the toad and other dark figures in the GLORIA account. These figures connect a landscape of animals with a landscape in the sky.",observe:"Explore the contrast between the bright band and dark dust clouds in a Milky Way image. For outdoor observation, choose southern skies, little moonlight, and very low light pollution.",source:["gloria"]}
];
