export const sourceNotes={
 simbad:["Coordenadas ICRS (época J2000) de las estrellas seleccionadas para las cartas. Cada estrella enlaza su ficha. No calculamos posiciones respecto del horizonte local.","ICRS coordinates (epoch J2000) for the stars selected for the charts. Each star links to its record. We do not calculate positions against the local horizon.","Siq’ikunapaq akllasqa quyllurkunapa ICRS, J2000 nisqa yupayninkuna. Sapa quyllur qillqanman t’inkisqam. Manam kitipa sayayninta yupanchikchu."],
 gloria:['Introducción educativa del proyecto GLORIA (2014), pp. 9–10: ejemplos de nombres y figuras oscuras. Es una síntesis, no un testimonio de todas las comunidades.','GLORIA project educational introduction (2014), pp. 9–10: examples of names and dark-cloud figures. A synthesis, not testimony from every community.','GLORIA (2014) yachachina qillqa, 9–10 raphi: sutikuna, yana rikch’akunawan. Manam llapan llaqtapa willakuyninchu.'],
 smithsonian:['Museo Nacional del Indígena Americano: Inti, Colca y celebraciones andinas. Contexto cultural de festividades vivas.','National Museum of the American Indian: Inti, Colca, and Andean celebrations. Cultural context for living festivals.','National Museum of the American Indian: Inti, Colca, Andeskunaq rayminkunawan.'],
 garcilaso:['Comentarios reales, primera parte, libro III, capítulo XXI. Fuente colonial que registra Chasca para Venus; requiere lectura histórica crítica.','Comentarios reales, first part, book III, chapter XXI. Colonial source recording Chasca for Venus; requires critical historical reading.','Comentarios reales, I, III, XXI. Ñawpa qillqapi Chascaqa Venus nisqam. Ñawpa pachanta yuyarispa ñawinchay.'],
 pucp:['Artículo de Anthropologica (PUCP), con identificaciones y variantes como Llamacñawin. Registra más de un grupo estelar bajo Collca.','Anthropologica (PUCP) article, with identifications and variants including Llamacñawin. Records more than one star group under Collca.','Anthropologica (PUCP) qillqa: Llamacñawin hina sutikuna. Collca sutipi hukniray quyllur huñukuna kachkan.'],
 nasa:['Consejos de observación a simple vista, adaptación a la oscuridad y planificación. Es astronomía práctica moderna.','Advice on naked-eye observation, dark adaptation, and preparation. Modern practical astronomy.','Ñawillawan qhaway, tutaman yachay, wakichikuywan. Kunan quyllur yachaymi.'],
 stellarium:['Guía oficial del planetario: lugar, fecha, hora y búsqueda de objetos. Una simulación debe identificarse como tal.','Official planetarium guide: location, date, time, and object search. A simulation should be identified as such.','Planetariopa pusana qillqan: kiti, punchaw, pacha, maskhaywan. Simulación kaptin chayta riqsichiy.'],
 minedu:['MINEDU, Urin qichwa qillqay: referencia sobre escritura del quechua sureño. No implica que el ministerio haya revisado o avalado las traducciones de Mayu.','MINEDU, Urin qichwa qillqay: reference on Southern Quechua writing. This does not mean the ministry reviewed or endorsed Mayu’s translations.','MINEDU, Urin qichwa qillqay: urin runasimi qillqaymanta. Manam MINEDU Mayupa tikrasqanta qhawarirqanchu.']
} as const;
